trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'DockerHUb'
        repository: 'thiagomartinsemartins/deskflora'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
- stage: Deploy
  displayName: Deploy
  jobs:
    - job: Deploy
      displayName: Deploy
      pool:
        name: Default
        vmImage: ubuntu-latest
      steps:
      - script: |
          echo "Parando o contêiner antigo..."
          docker stop $(docker ps -q --filter ancestor=thiagomartinsemartins/deskflora) || true
          echo "Removendo o contêiner antigo..."
          docker rm $(docker ps -aq --filter ancestor=thiagomartinsemartins/deskflora) || true
          echo "Puxando a nova imagem do Docker Hub..."
          docker pull thiagomartinsemartins/deskflora:$(tag)
          echo "Iniciando o novo contêiner..."
          docker run -d -p 8080:80 thiagomartinsemartins/deskflora:$(tag)
        displayName: 'Implantar no servidor'
