trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'DockerHUb'
        repository: 'thiagomartinsemartins/deskflora'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
- stage: Deploy
  displayName: Deploy
  jobs:
    - job: Deploy
      displayName: Deploy
      pool:
        name: Default
        vmImage: ubuntu-latest
      steps:
        - script: |
            echo "parando container"
            docker stop $(docker ps -q --filter "ancestor=thiagomartinsemartins/deskflora") 
            echo "Pulling the new image from Docker Hub..."
            docker pull thiagomartinsemartins/deskflora:$(tag)
            echo "Starting the new container..."
            docker run -d -p 8080:80 thiagomartinsemartins/deskflora:$(tag)
          displayName: 'Deploy container'
#--filter "publish=$PORT:80"
