trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'DockerHUb'
        repository: 'thiagomartinsemartins/deskflora'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
- stage: Deploy
  displayName: Deploy
  jobs:
    - job: Deploy
      displayName: Deploy
      pool:
        name: Default
        vmImage: ubuntu-latest
      steps:
        - script: |
            PORT=8080
            if lsof -Pi :$PORT -sTCP:LISTEN -t >/dev/null; then
                echo "Port $PORT is already in use."
                echo "Stopping the old container using port $PORT..."
                docker stop $(docker ps -q --filter "ancestor=thiagomartinsemartins/deskflora" --filter "publish=$PORT:80") || true
            fi

            echo "Pulling the new image from Docker Hub..."
            docker pull thiagomartinsemartins/deskflora:$(tag)
            echo "Starting the new container..."
            docker run -d -p $PORT:80 thiagomartinsemartins/deskflora:$(tag)
          displayName: 'Deploy container'

