# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'DockerHUb'
        repository: 'thiagomartinsemartins/deskflora'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
- stage: Deploy
  displayName: Deploy
  jobs:
    - job: Deploy
      displayName: Deploy
      pool:
        name: Default
        vmImage: ubuntu-latest
      steps:
      - script: |
          docker pull thiagomartinsemartins/deskflora:latest
          docker run -d -p 8080:80 thiagomartinsemartins/deskflora:latest
        displayName: 'Implantar no servidor'